app = "twitch-search-server"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/search?title=luckyv"

[[metrics]]
port = 8000
path = "/metrics"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
  cpus = 1