openapi: 3.0.0
info:
  description: This is a API for the Twitch-Search-Server
    (https://github.com/Nickwasused/twitch-search-server).
  version: 1.0.0
  title: twitch-search-server
  termsOfService: ""
  contact:
    email: contact.nickwasused.fa6c8@simplelogin.co
  license:
    name: Mozilla Public License 2.0
    url: https://github.com/Nickwasused/twitch-search-server/blob/main/LICENSE
paths:
  /search:
    get:
      summary: Search for Streams
      description: Multiple search parameters can be provided.
      operationId: search
      parameters:
        - name: id
          in: query
          description: Stream ID
          required: false
          schema:
            type: integer
        - name: user_id
          in: query
          description: ID of the user who is streaming.
          required: false
          schema:
            type: integer
        - name: user_login
          in: query
          description: Login of the user who is streaming.
          required: false
          schema:
            type: string
        - name: user_name
          in: query
          description: Display name corresponding to user_id.
          required: false
          schema:
            type: string
        - name: game_id
          in: query
          description: ID of the game being played on the stream.
          required: false
          schema:
            type: integer
        - name: game_name
          in: query
          description: Name of the game being played.
          required: false
          schema:
            type: string
        - name: type
          in: query
          description: 'Stream type: "live" or "" (in case of error).'
          required: false
          schema:
            type: string
        - name: title
          in: query
          description: Stream title.
          required: false
          schema:
            type: string
        - name: started_at
          in: query
          description: UTC timestamp.
          required: false
          schema:
            type: integer
        - name: language
          in: query
          description: Stream language. A language value is either the ISO 639-1 two-letter
            code for a supported stream language or “other”.
          required: false
          schema:
            type: integer
        - name: thumbnail_url
          in: query
          description: Thumbnail URL of the stream. All image URLs have variable width and
            height. You can replace {width} and {height} with any values to get
            that size image
          required: false
          schema:
            type: integer
        - name: tag_ids
          in: query
          description: Shows tag IDs that apply to the stream.
          required: false
          schema:
            type: array
            items:
              type: integer
        - name: is_mature
          in: query
          description: Indicates if the broadcaster has specified their channel contains
            mature content that may be inappropriate for younger audiences.
          required: false
          schema:
            type: integer
      responses:
        '200':
            description: Response Object
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Response'
        "401":
          description: setup required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'
                
  /code:
    get:
      summary: Twitch auth
      description: You get redirected here during the setup.
      operationId: code
      parameters:
        - name: code
          in: query
          description: Twitch Auth Code
          required: false
          schema:
            type: integer
        - name: state
          in: query
          description: State generated by the API.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: code and state accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'
        "403":
          description: wrong state returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'
        "500":
          description: wrong/no code send
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'
          
  /setup:
    get:
      summary: API Setup
      description: This is required to get the Server up and running.
      operationId: setup
      responses:
        "200":
          description: the setup is completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'
        "301":
          description: redirect to Twitch login after that you get redirected to /code
          
  /metrics:
    get:
      summary: Prometheus Metrics
      description: Not that this is running on another Port (9210) and not on 3000.
      operationId: metrics
      responses:
        "200":
          description: you got metrics

components:
  schemas:
    Response:
      type: object
      properties:
        status:
          type: string
          description: done, setup, error
        data:
          $ref: '#/components/schemas/StreamerList'
          
    SimpleResponse:
      type: object
      properties:
        status:
          type: string
          description: done, setup, error
            
          
    StreamerList:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            description: Stream ID
          user_id:
            type: string
            description: ID of the user who is streaming.
          user_login:
            type: string
            description: Login of the user who is streaming.
          user_name:
            type: string
            description: Display name corresponding to user_id.
          game_id:
            type: string
            description: ID of the game being played on the stream.
          game_name:
            type: string
            description: Name of the game being played.
          type:
            type: string
            description: 'Stream type: "live" or "" (in case of error).'
          title:
            type: string
            description: Stream title.
          viewer_count:
            type: integer
            description: The current viewer count of the stream
          started_at:
            type: string
            description: UTC timestamp.
          language:
            type: string
            description: Stream language. A language value is either the ISO 639-1 two-letter code for a supported stream language or “other”.
          thumbnail_url:
            type: string
            description: Thumbnail URL of the stream. All image URLs have variable width and height. You can replace {width} and {height} with any values to get
          tag_ids:
            type: array
            description: Shows tag IDs that apply to the stream.
            items:
              type: integer
          is_mature:
            type: boolean
            description: Indicates if the broadcaster has specified their channel contains mature content that may be inappropriate for younger audiences.
          
              

servers:
  - url: https://twitch-search-server.nickwasused.com/
    description: "[DE][GTA5]"
  - url: https://twitch-search-server-en.nickwasused.com/
    description: "[EN][GTA5]"